### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jmesserly**
the tests run standalone, Dart SVN checkout not required :)

### CODE REVIEW

**Comment by jmesserly** [comment]
R= @kevmoo @sigmundch

**Comment by jmesserly** [comment]
and fwiw, the shell script is basically just "dartanalyzer" and "dart -c test/run_all.dart" ... so windows users shouldn't have too much trouble.

**Comment by sigmundch** [comment]
lgtm - we should set up a travis for this package. We have the test running in the package bots too, but it will be simpler for our users to see how it's run automatically that way.

**Comment by jmesserly** [comment]
+100

**Pull request merged**
