### PR TITLE
fix some deprecation warnings

### PR DESCRIPTION
**Pull request by devoncarew**

### CODE REVIEW

**Comment by devoncarew** [comment]
@kevmoo @jmesserly @sigmundch

**Comment by kevmoo** [comment]
Are we okay dropping stable from future releases of this package?

If so, need to update the min SDK constraint and drop stable from `.travis.yml`

**Comment by devoncarew** [comment]
Given the test failures here: https://travis-ci.org/dart-lang/html/builds/351548983?utm_source=github_status&utm_medium=notification, I think we need to disable testing against the 1.24 sdk (and bump the sdk constraint).

**Comment by devoncarew** [comment]
Yeah, or I could drop this PR - this only addresses deprecation warnings.

**Comment by devoncarew** [comment]
closing for now

**Pull request closed without merging**
